name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install the dependencies
        run: |
          python -m pip install -r requirements.txt
      
      - name: Build the JupyterLite site
        run: |
          mkdir -p content
          cp README.md content
          # echo "print(Hello, JupyterLite!)" > content/test.py
          jupyter lite build --contents content --output-dir dist
      
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.2.1
        with:
          branch: gh-pages
          commit-message: 'Update JupyterLite'
          folder: dist
          clean: false
